<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityManager;
/**
 * MenuLikeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuLikeRepository extends \Doctrine\ORM\EntityRepository
{
  /**
   * [findNotesById Retourne toutes les notes d'un menu]
   * @param  [int] $id [Identifiant du menu]
   * @return [type]     [description]
   */
  public function findNotesById($id){
    return $this
    ->createQueryBuilder('n')
    ->select('n.rating')
    ->where("n.menu= :id")
    ->setParameter('id',$id)
    ->getQuery()
    ->getResult();
  }

/**
 * [countNotesById Retourne le nombre de notes d'un menu]
 * @param  int $id Identificant du menu
 * @return int   nombre de notes
 */
  public function countNotesById($id){
  return $this->createQueryBuilder('c')
    ->select('count(c.id)')
    ->where('c.menu = :id')
    ->setParameter('id', $id)
    ->getQuery()
    ->getSingleScalarResult();
  }


}
