<?php

namespace AppBundle\Repository;

/**
 * MenuLikeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuLikeRepository extends \Doctrine\ORM\EntityRepository
{
}
