<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityManager;
/**
 * MenuLikeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuLikeRepository extends \Doctrine\ORM\EntityRepository
{
  public function findNotesById($id){
    return $this
    ->createQueryBuilder('n')
    ->select('n.rating')
    ->where("n.menu= :id")
    ->setParameter('id',$id)
    ->getQuery()
    ->getResult();
  }

  public function countNotesById($id){
  return $this->createQueryBuilder('c')
    ->select('count(c.id)')
    ->where('c.menu = :id')
    ->setParameter('id', $id)
    ->getQuery()
    ->getSingleScalarResult();
  }

  
}
