# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    app.notes:
#        class: AppBundle\Services\Notes
#        arguments: [ '@doctrine.orm.entity_manager' ]
    app.notes:
        class: AppBundle\Services\Notes
        arguments: [ '@doctrine' ]

    app.menu_like_extension:
        class: AppBundle\Twig\MenuLikeExtension
        tags:
            - { name: twig.extension }
        arguments: ['@app.notes']
