# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.notes:
        class: AppBundle\Services\Notes
        arguments: [ '@doctrine.orm.entity_manager' ]
